### ISSUE TITLE
Invalid ceserver version. ()

### ISSUE THREAD

**Issue by kamuran21** [holly-hacker/ce-server#2]
When I try to connect from client to server, client returns "Invalid ceserver version. ()" error and
 
the server print this: 
```
14:28:12 [INFO] New socket opened: 192.168.1.1:56995
14:28:37 [ERROR] Unimplemented packet byte 0 (data: [])
thread 'tokio-runtime-worker' panicked at src\server\server.rs:88:9:
not yet implemented: Unimplemented packet byte 0
```

**Comment by holly-hacker** [comment]
For people with the same error, Cheat Engine 7.2 should in theory work.

**Comment by friedthewires** [comment]
> For people with the same error, Cheat Engine 7.2 should in theory work.

Thank You, you are awesome!

**Comment by soryu0412-create** [comment]
@kamuran21 @holly-hacker 


Has anyone succeeded?

My head hurts so much><

I tried versions 7.2, 7.4, and 7.6, but none of them worked.

thread 'tokio-runtime-worker' (4520) panicked at src\server\server.rs:88:9:

not yet implemented: Unimplemented packet byte 37

02:15:26 [INFO] New socket opened: 192.168.73.1:59933

02:15:26 [INFO] New socket opened: 192.168.73.1:59934

02:15:31 [ERROR] failed to read from socket; err = Os { code: 10054, kind: ConnectionReset, message:

The CE end also throws an error and cannot be used.

**Comment by holly-hacker** [comment]
I've started looking into updating ce-server to Cheat Engine v7.7 as it now natively supports Linux, but it seems the Cheat Engine source code on GitHub is deliberately kept out of date which means I can't implement the latest version of the protocol.

I'm also getting more annoyed at the nags and deliberate annoyances that the "trial" version of Cheat Engine [now seems to include](https://www.cheatengine.org/forum/viewtopic.php?p=5763698&sid=9b7823d1d9ba4e63b319ab7cb6646ff2) (such as deliberately turning off features or even the entire window).

I've pushed some changes to the `feat/bring-up-to-date` branch which should in theory support some version of v7.6.x (protocol version 6), but I don't know exactly which since v7.6.6 seems to have made breaking changes to the protocol as well. Feel free to try it out and report your results.
